version: '3.8'

services:
  web:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"

  php:
    image: php:fpm
    volumes:
      - ./html:/usr/share/nginx/html

